### PR TITLE
Codenvy minimal and standard assembly docs

### PR DESCRIPTION
**Pull request by skabashnyuk**
Issue https://github.com/codenvy/codenvy/pull/2060

### CODE REVIEW

**Comment by bmicklea** [comment]
I don't mind putting this into the .md files if needed, but I don't understand this capability well enough to know where in the docs this section belongs. Please comment with the URL of the page and name of the section that this should replace or follow.

**Comment by skabashnyuk** [comment]
@bmicklea I don't understand you question.

**Comment by bmicklea** [comment]
It's okay - after doing the Che docs I understand what needs to happen here.

**Comment by bmicklea** [comment]
Closing this without merging as these docs were added as part of the Che PR: https://github.com/eclipse/che-docs/pull/202

**Pull request closed without merging**
