### PR TITLE
Monitoring using Zabbix and pingdom

### PR DESCRIPTION
**Pull request by skryzhny**
Resolves: https://github.com/codenvy/docs/issues/2

### CODE REVIEW

**Comment by skryzhny** [comment]
https://github.com/codenvy/docs/issues/2

**Comment by skryzhny** [comment]
I need to share above-mentioned zabbix templates publicly.
Is it OK to add it here?

**Comment by bmicklea** [comment]
Yes, no problem

**Comment by eivantsov** [comment]
@bmicklea can you please review? Mostly language and grammar. I am OK with the content.

**Pull request merged**
