### PR TITLE
Create a troubleshooting guide

### PR DESCRIPTION
**Pull request by bmicklea**

### CODE REVIEW

**Comment by bmicklea** [comment]
@eivantsov can you add some other things to this?

**Comment by TylerJewell** [comment]
@bmicklea @eivantsov - I do not think we should complete this guide.  I would rather see us making improvements to the key areas during the installation or configuration sections to cover likely scenarios that would cause this.  We can articulate all of these problems and either document them in-context or add CLI help to solve this.

**Comment by bmicklea** [comment]
The downside with that approach is that for a user who isn't using the docs as they run into the issue they have to accurately guess where the problem is to find the troubleshooting hints. For example if I've had a smooth install and not needed or read the docs, but my my workspace doesn't start I have I accurately guess that there are suggestions in the networking section. A single troubleshooting section was planned to include both concrete advice and links to other appropriate sections to guide users to content we might already have there.

**Comment by TylerJewell** [comment]
Yep.  I am ok with thay

**Comment by bmicklea** [comment]
Closing without merging.

**Pull request closed without merging**
